import PageHeader from "../components/ui/PageHeader";
import SectionCard from "../components/ui/SectionCard";
import IncidentTable from "../features/incidents/components/IncidentTable";

function IncidentsPage() {
  return (
    <>
      <PageHeader
        title="Incidents"
        description="Review suspicious player activity, inspect incident severity, and manage case status for flagged events."
        badge="Moderator Workflow"
      />

      <SectionCard
        title="Incident Queue"
        description="Search, filter, and review suspicious incidents generated by the anti-cheat detection pipeline."
      >
        <IncidentTable />
      </SectionCard>
    </>
  );
}

export default IncidentsPage;