import type {
  ApiLiveStatusRecord,
  ApiRouteRecord,
  ApplicationHealthSummary,
  CommunicationMetrics,
  EndpointTestScenario,
  ObservabilitySnapshot,
  RequestLogRecord,
  ResourcePoint,
  TrafficPoint,
} from "../../types/observability";

export const observabilityRoutes: ApiRouteRecord[] = [
  {
    id: "auth-login",
    path: "/api/v1/auth/login",
    method: "POST",
    module: "Authentication",
    authRequired: false,
    description: "Authenticates administrators and returns an access token.",
    availability: "Available",
    lastTestResult: "Passed",
    averageLatencyMs: 118,
    lastCheckedAt: "2026-04-24 19:42 UTC",
  },
  {
    id: "dashboard-overview",
    path: "/api/v1/dashboard/overview",
    method: "GET",
    module: "Dashboard",
    authRequired: true,
    description: "Returns top-level dashboard KPIs, charts, and summary widgets.",
    availability: "Available",
    lastTestResult: "Passed",
    averageLatencyMs: 84,
    lastCheckedAt: "2026-04-24 19:41 UTC",
  },
  {
    id: "incidents-create",
    path: "/api/v1/incidents",
    method: "POST",
    module: "Incidents",
    authRequired: true,
    description: "Creates a new incident report and stores it in the incident pipeline.",
    availability: "Degraded",
    lastTestResult: "Warning",
    averageLatencyMs: 236,
    lastCheckedAt: "2026-04-24 19:39 UTC",
  },
  {
    id: "players-list",
    path: "/api/v1/players",
    method: "GET",
    module: "Players",
    authRequired: true,
    description: "Fetches paginated user and player records for administration.",
    availability: "Available",
    lastTestResult: "Passed",
    averageLatencyMs: 97,
    lastCheckedAt: "2026-04-24 19:40 UTC",
  },
  {
    id: "audit-logs",
    path: "/api/v1/audit/logs",
    method: "GET",
    module: "Audit",
    authRequired: true,
    description: "Retrieves audit log records for moderator actions and system events.",
    availability: "Available",
    lastTestResult: "Passed",
    averageLatencyMs: 132,
    lastCheckedAt: "2026-04-24 19:42 UTC",
  },
  {
    id: "health-check",
    path: "/api/v1/health",
    method: "GET",
    module: "Infrastructure",
    authRequired: false,
    description: "Returns backend, DynamoDB, storage, and worker health indicators.",
    availability: "Available",
    lastTestResult: "Passed",
    averageLatencyMs: 41,
    lastCheckedAt: "2026-04-24 19:42 UTC",
  },
];

export const observabilityLiveStatuses: ApiLiveStatusRecord[] = [
  {
    id: "live-auth",
    routeId: "auth-login",
    label: "Admin Login",
    state: "Online",
    statusCode: 200,
    latencyMs: 112,
    lastCheckedAt: "19:42:11 UTC",
    success: true,
  },
  {
    id: "live-dashboard",
    routeId: "dashboard-overview",
    label: "Dashboard Overview",
    state: "Online",
    statusCode: 200,
    latencyMs: 78,
    lastCheckedAt: "19:42:03 UTC",
    success: true,
  },
  {
    id: "live-incidents",
    routeId: "incidents-create",
    label: "Incident Submission",
    state: "Degraded",
    statusCode: 202,
    latencyMs: 244,
    lastCheckedAt: "19:41:56 UTC",
    success: true,
  },
  {
    id: "live-players",
    routeId: "players-list",
    label: "Player Directory",
    state: "Online",
    statusCode: 200,
    latencyMs: 96,
    lastCheckedAt: "19:42:08 UTC",
    success: true,
  },
  {
    id: "live-audit",
    routeId: "audit-logs",
    label: "Audit Retrieval",
    state: "Online",
    statusCode: 200,
    latencyMs: 136,
    lastCheckedAt: "19:42:01 UTC",
    success: true,
  },
  {
    id: "live-health",
    routeId: "health-check",
    label: "Health Probe",
    state: "Online",
    statusCode: 200,
    latencyMs: 43,
    lastCheckedAt: "19:42:10 UTC",
    success: true,
  },
];

export const observabilityEndpointTests: EndpointTestScenario[] = [
  {
    id: "test-login",
    label: "Login Authentication",
    routeId: "auth-login",
    method: "POST",
    payloadTemplate: JSON.stringify(
      { email: "admin@fairplay.cloud", password: "demo-password" },
      null,
      2,
    ),
    description: "Verifies authentication, token issuance, and baseline auth latency.",
  },
  {
    id: "test-dashboard",
    label: "Fetch Dashboard Data",
    routeId: "dashboard-overview",
    method: "GET",
    payloadTemplate: JSON.stringify({ region: "global" }, null, 2),
    description: "Checks the dashboard summary endpoint used by the admin homepage.",
  },
  {
    id: "test-incidents",
    label: "Submit Incident",
    routeId: "incidents-create",
    method: "POST",
    payloadTemplate: JSON.stringify(
      {
        source: "manual-review",
        severity: "high",
        summary: "Suspicious movement burst detected in scrim lobby.",
      },
      null,
      2,
    ),
    description: "Exercises the incident creation path and persistence pipeline.",
  },
  {
    id: "test-players",
    label: "Fetch Users / Players",
    routeId: "players-list",
    method: "GET",
    payloadTemplate: JSON.stringify({ page: 1, limit: 20 }, null, 2),
    description: "Confirms player directory responses and pagination.",
  },
  {
    id: "test-audit",
    label: "Logs / Audit Retrieval",
    routeId: "audit-logs",
    method: "GET",
    payloadTemplate: JSON.stringify({ range: "24h" }, null, 2),
    description: "Tests audit visibility for compliance and admin investigations.",
  },
  {
    id: "test-health",
    label: "Health Check Endpoint",
    routeId: "health-check",
    method: "GET",
    payloadTemplate: JSON.stringify({ includeDependencies: true }, null, 2),
    description: "Checks application, storage, and DynamoDB readiness probes.",
  },
];

export const applicationHealthSummary: ApplicationHealthSummary = {
  backendStatus: "Healthy",
  databaseStatus: "Healthy",
  storageStatus: "Warning",
  uptime: "12d 04h 18m",
  memoryUse: "1.84 GB / 4 GB",
  cpuLoad: "43%",
  requestErrorRate: "0.9%",
  healthSummaryScore: 91,
};

export const communicationMetrics: CommunicationMetrics = {
  totalRequestsSent: "184.2K",
  totalResponsesReceived: "183.6K",
  failedResponses: "1.4K",
  timeoutCount: "97",
  retryCount: "318",
  averageRoundTripTime: "126 ms",
  bytesSent: "2.6 GB",
  bytesReceived: "9.8 GB",
  activeConnections: "48",
  connectionStability: "Stable",
};

export const resourceTrend: ResourcePoint[] = [
  { time: "13:00", memory: 61, cpu: 38, errorRate: 0.6 },
  { time: "14:00", memory: 64, cpu: 41, errorRate: 0.5 },
  { time: "15:00", memory: 68, cpu: 46, errorRate: 0.9 },
  { time: "16:00", memory: 66, cpu: 44, errorRate: 0.8 },
  { time: "17:00", memory: 72, cpu: 51, errorRate: 1.2 },
  { time: "18:00", memory: 69, cpu: 47, errorRate: 0.7 },
  { time: "19:00", memory: 71, cpu: 43, errorRate: 0.9 },
];

export const trafficTrend: TrafficPoint[] = [
  { time: "13:00", requests: 1120, responses: 1107, failed: 13, avgRtt: 118, bytesSentKb: 182, bytesReceivedKb: 822 },
  { time: "14:00", requests: 1246, responses: 1231, failed: 15, avgRtt: 121, bytesSentKb: 196, bytesReceivedKb: 874 },
  { time: "15:00", requests: 1384, responses: 1366, failed: 18, avgRtt: 129, bytesSentKb: 221, bytesReceivedKb: 964 },
  { time: "16:00", requests: 1310, responses: 1294, failed: 16, avgRtt: 125, bytesSentKb: 208, bytesReceivedKb: 913 },
  { time: "17:00", requests: 1498, responses: 1471, failed: 27, avgRtt: 136, bytesSentKb: 236, bytesReceivedKb: 1014 },
  { time: "18:00", requests: 1433, responses: 1418, failed: 15, avgRtt: 123, bytesSentKb: 214, bytesReceivedKb: 948 },
  { time: "19:00", requests: 1510, responses: 1492, failed: 18, avgRtt: 127, bytesSentKb: 241, bytesReceivedKb: 1056 },
];

export const requestLogs: RequestLogRecord[] = [
  {
    id: "log-1",
    timestamp: "19:42:11",
    method: "POST",
    route: "/api/v1/auth/login",
    statusCode: 200,
    durationMs: 112,
    bytesSentKb: 3.8,
    bytesReceivedKb: 6.2,
    traceId: "trc-auth-9831",
    message: "Token issuance completed for administrator login challenge.",
  },
  {
    id: "log-2",
    timestamp: "19:42:08",
    method: "GET",
    route: "/api/v1/players",
    statusCode: 200,
    durationMs: 96,
    bytesSentKb: 1.4,
    bytesReceivedKb: 42.7,
    traceId: "trc-players-4412",
    message: "Player roster page 1 retrieved with active moderation flags.",
  },
  {
    id: "log-3",
    timestamp: "19:42:03",
    method: "GET",
    route: "/api/v1/dashboard/overview",
    statusCode: 200,
    durationMs: 78,
    bytesSentKb: 1.1,
    bytesReceivedKb: 34.6,
    traceId: "trc-dash-2214",
    message: "Dashboard KPI aggregate served from cached summary store.",
  },
  {
    id: "log-4",
    timestamp: "19:41:56",
    method: "POST",
    route: "/api/v1/incidents",
    statusCode: 202,
    durationMs: 244,
    bytesSentKb: 5.2,
    bytesReceivedKb: 2.4,
    traceId: "trc-inc-7742",
    message: "Incident queued successfully while storage acknowledgement remained delayed.",
  },
  {
    id: "log-5",
    timestamp: "19:41:50",
    method: "GET",
    route: "/api/v1/audit/logs",
    statusCode: 200,
    durationMs: 136,
    bytesSentKb: 1.3,
    bytesReceivedKb: 27.9,
    traceId: "trc-audit-1183",
    message: "Audit records streamed to admin console for 24 hour window.",
  },
];

export const observabilitySnapshot: ObservabilitySnapshot = {
  routes: observabilityRoutes,
  liveStatuses: observabilityLiveStatuses,
  endpointTests: observabilityEndpointTests,
  applicationHealth: applicationHealthSummary,
  communicationMetrics,
  resourceTrend,
  trafficTrend,
  requestLogs,
};
